# Generated by Django 3.1 on 2022-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_reviewrationg'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrationg',
            name='username_add_to',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
