# Generated by Django 3.1 on 2022-08-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_is_verif'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_step1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_step2',
            field=models.BooleanField(default=False),
        ),
    ]
