# Generated by Django 3.1 on 2022-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220816_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangepasswordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('verify_password', models.CharField(max_length=100)),
            ],
        ),
    ]
