# Generated by Django 3.1 on 2022-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='access_level',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0),
        ),
    ]
