# Generated by Django 3.1 on 2022-07-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
    ]
